DEVICE          : cuda                        # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : '/mnt/../code/stitchfusion/checkpoints_training//stitchfusion_mfnet'          # output folder name used for saving the model, logs and inference results
GPUs            : 4
GPU_IDs         : [0,1,2,3]
USE_WANDB       : False                       # Whether you want to use wandb
WANDB_NAME      : 'stitchfusion-MFNet-RGBT'        # name for the run

MODEL:
  NAME          : stitchfusion                                         # name of the model you are using
  BACKBONE      : stitchfusion-B4                                      # model variant
  PRETRAINED    : '/mnt/../code/stitchfusion/checkpoints/pretrained/segformers/mit_b4.pth'     # backbone model's weight 
  RESUME        : ''                                                # checkpoint file

DATASET:
  NAME          : MFNet                                            # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : '/mnt/../code/stitchfusion/data/MFNet'                            # dataset root path
  IGNORE_LABEL  : 255
  # MODALS        : ['image']
  MODALS        : ['img', 'ther']

TRAIN:
  IMAGE_SIZE    : [640, 480]      # training image size in (h, w) === Fixed in dataloader, following MCubeSNet
  BATCH_SIZE    : 12               # batch size used to train
  EPOCHS        : 250             # number of epochs to train
  EVAL_START    : 0               # evaluation interval during training
  EVAL_INTERVAL : 1               # evaluation interval during training
  AMP           : true            # use AMP in training
  DDP           : false           # use DDP training

LOSS:
  NAME          : OhemCrossEntropy # loss function name
  CLS_WEIGHTS   : false            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.00012            # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer 

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio
  

EVAL:
  MODEL_PATH    : '/mnt/../code/stitchfusion/checkpoints_val/stitchfusion_mfnet'                  # Path to your saved model
  IMAGE_SIZE    : [640, 480]                            # evaluation image size in (h, w)                       
  BATCH_SIZE    : 12                                       # batch size
  VIS_SAVE_DIR  : '/mnt/../code/stitchfusion/checkpoints_val/stitchfusion_mfnet'              # Where to save visualization
  MSF: 
    ENABLE      : false                                   # multi-scale and flip evaluation  
    FLIP        : true                                    # use flip in evaluation  
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]       # scales used in MSF evaluation                
